apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: machine
  template:
    metadata:
      labels:
        app: machine
      annotations:
        sidecar.opentelemetry.io/inject: "belastingdienst-machine-otlp-collector"
    spec:
      containers:
        - name: belastingdienst-machine
          image: belastingdienst-backend-image
          env:
            - name: APP_DEBUG
              value: "true"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: belastingdienst-db-app
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: belastingdienst-db-app
                  key: password
            - name: DB_HOST
              value: "belastingdienst-db-rw"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "app"
            - name: APP_ORGANIZATION
              value: "Belastingdienst"
            - name: DATABASE_URL
              value: "postgres://$(DB_USER):$(DB_PASS)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: services-config
              mountPath: /build/services
              readOnly: true
      volumes:
        - name: services-config
          configMap:
            name: services-cm
