apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        sidecar.opentelemetry.io/inject: "belastingdienst-backend-otlp-collector"
    spec:
      containers:
        - name: belastingdienst-backend
          image: go-engine-backend-image
          env:
            - name: APP_DEBUG
              value: "true"
            - name: APP_ORGANIZATION
              value: "Belastingdienst"
            - name: APP_STANDALONE_MODE
              value: "true"
            - name: APP_RULE_SERVICE_IN_MEMORY
              value: "false"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://localhost:4317"
            - name: OTEL_SERVICE_NAME
              value: "Belastingdienst"
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: services-config
              mountPath: /build/services
              readOnly: true
      volumes:
        - name: services-config
          configMap:
            name: services-cm
