apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lac
namePrefix: rvz-

patches:
  - target:
      kind: Ingress
      name: backend-ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: rvz-backend.127-0-0-1.nip.io
      - op: remove
        path: /spec/tls

resources:
  - ../../base
