apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: backend-

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

labels:
  - includeSelectors: true
    pairs:
      app: backend
      service: KVK
