stages:
  - deploy

build-image:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  script:
    - /kaniko/executor
      --context="${CI_PROJECT_DIR}"
      --dockerfile="${CI_PROJECT_DIR}/Dockerfile"
      --destination="${DOCKER_REGISTRY_HOST}/${CI_PROJECT_PATH}/poc:latest"
      --cache="true"
      --cache-ttl="168h"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
