services:
  - name: BRP
    endpoint: https://toeslagen-fsc-outway.padv.apps.digilab.network
    grant_hash: $1$3$VO-jHwZkOOy-raSIW0kXYW31Up5r8os49xwm3zaez8f0ykJ_c8DlZNzL8B7oVzxjjoUVxHhErQSIlZXERgOx6A
    rvva_id: 31953ef2-5a52-421a-9d2d-2c11e6dcb86f
  - name: RVZ
    endpoint: https://toeslagen-fsc-outway.padv.apps.digilab.network
    grant_hash: $1$3$VA4UnScQwU0uLM9gqicTs6HQmuOY6UDXZAWSxInn3uEru0dRkyTRirqpfX4HPUZvsSLUctRlwCQ1e7Vnh74smw
    rvva_id: 82ece16c-f848-4f8c-aa18-a90bf2d91c07
  - name: DJI
    endpoint:
    grant_hash:
    rvva_id:
  - name: UWV
    endpoint: https://toeslagen-fsc-outway.padv.apps.digilab.network
    grant_hash: $1$3$yr4FU7PHPI42xvTbYaMtRSQM_q8K0N9S4upmFI9GvxBZYeS1SB0pip3GvBoshXRhbXHx7P8ZEXNPgH5I_KF0xA
    rvva_id: d5ec9dc2-004f-46c8-9c04-a746f273ae5e
  - name: BELASTINGDIENST
    endpoint: https://toeslagen-fsc-outway.padv.apps.digilab.network
    grant_hash: $1$3$cOHAor-pfjk454KCZVcplaTZyQdnmlPzCujEE9Oq3owRaDZAIVH9_Ce7GExrsPmxiQbC8sIM0LY40t3NcfF1Qw
    rvva_id: 9809921f-eb9c-4f88-adf9-51c82b364a01
  - name: DUO
    endpoint: https://toeslagen-fsc-outway.padv.apps.digilab.network
    grant_hash: $1$3$Sp0A6luf1SgVoi28mUrUB013KCKgIae8nUUQe24bnN18xVc0mR3lVlwOD1b_cOrfy7gjw-UGy8hO1uP8ihqdJA
    rvva_id: 54f6a690-d7f5-4dc9-9ec9-af00e336bf6a
