apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: lac
build:
  local:
    push: false
    useDockerCLI: true
  artifacts:
    - image: belastingdienst-backend-image
      context: apps/belastingdienst/backend
      docker:
        dockerfile: apps/belastingdienst/backend/dev.Dockerfile
      sync:
        manual:
          - src: "**/*.go"
            dest: /build
    - image: go-engine-image
      context: .
      docker:
        dockerfile: machinev2/backend/dev.Dockerfile
      sync:
        manual:
          - src: "machinev2/**/*.go"
            dest: /build
            strip: "machinev2"
    - image: web-image
      context: .
      docker:
        dockerfile: dev.Dockerfile
      sync:
        manual:
          - src: "**/*.py"
            dest: /app

manifests:
  kustomize:
    paths:
      - deploy/manifests/rijksoverheid/overlays/local
      - deploy/manifests/overlays/local
