apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: machine-

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - otlp-collector.yaml

labels:
  - includeSelectors: true
    pairs:
      app: machine
      service: RvIG
