apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: verifier-

resources:
  - database.yaml
  - deployment.yaml
  - ingress.yaml
  - service.yaml

labels:
  - includeSelectors: true
    pairs:
      component: verifier
