apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: inzicht-backend-

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

labels:
  - includeSelectors: true
    pairs:
      app: inzicht-backend
      service: Toeslagen
