engines:
  - id: py
    name: Python engine
    description: default processing engine
    type: internal
  - id: http-go
    name: Go engine
    description: typed processing engine (beta)
    type: http
    domain: http://toeslagen-machine-svc/v0
    service_routing:
      enabled: false
  - id: http-go-routing
    name: Go engine with routing
    description: typed processing engine (beta)
    type: http
    domain: http://toeslagen-machine-svc/v0
    default: true
    service_routing:
      enabled: true
      # When enabled, routes requests to different services based on service name
      services:
        BELASTINGDIENST:
          domain: http://belastingdienst-machine-svc.lac.svc.cluster.local/v0
        CBS:
          domain: http://cbs-machine-svc.lac.svc.cluster.local/v0
        DJI:
          domain: http://dji-machine-svc.lac.svc.cluster.local/v0
        DUO:
          domain: http://duo-machine-svc.lac.svc.cluster.local/v0
        GEMEENTE_AMSTERDAM:
          domain: http://gemeente-amsterdam-machine-svc.lac.svc.cluster.local/v0
        IND:
          domain: http://ind-machine-svc.lac.svc.cluster.local/v0
        JUSTID:
          domain: http://justid-machine-svc.lac.svc.cluster.local/v0
        JenV:
          domain: http://jenv-machine-svc.lac.svc.cluster.local/v0
        KIESRAAD:
          domain: http://kiesraad-machine-svc.lac.svc.cluster.local/v0
        KVK:
          domain: http://kvk-machine-svc.lac.svc.cluster.local/v0
        RVZ:
          domain: http://rvz-machine-svc.lac.svc.cluster.local/v0
        RvIG:
          domain: http://rvig-machine-svc.lac.svc.cluster.local/v0
        SVB:
          domain: http://svb-machine-svc.lac.svc.cluster.local/v0
        SZW:
          domain: http://szw-machine-svc.lac.svc.cluster.local/v0
        TOESLAGEN:
          domain: http://toeslagen-machine-svc.lac.svc.cluster.local/v0
        UWV:
          domain: http://uwv-machine-svc.lac.svc.cluster.local/v0
        VWS:
          domain: http://vws-machine-svc.lac.svc.cluster.local/v0
