// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CaseStatus.
const (
	DECIDED   CaseStatus = "DECIDED"
	INREVIEW  CaseStatus = "IN_REVIEW"
	OBJECTED  CaseStatus = "OBJECTED"
	SUBMITTED CaseStatus = "SUBMITTED"
)

// Case Claim
type Case struct {
	Approved *bool `json:"approved,omitempty"`

	// Bsn Burgerservicenummer of a Dutch citizen
	Bsn Bsn `json:"bsn"`

	// Law Specify the law that needs to be executed
	Law string `json:"law"`

	// Service Specify the service that needs to be executed
	Service string     `json:"service"`
	Status  CaseStatus `json:"status"`
}

// CaseStatus defines model for Case.Status.
type CaseStatus string

// CaseList List of all cases
type CaseList = []Case

// Claim Claim
type Claim struct {
	// Bsn Burgerservicenummer of a Dutch citizen
	Bsn Bsn    `json:"bsn"`
	Key string `json:"key"`

	// Law Specify the law that needs to be executed
	Law string `json:"law"`

	// Service Specify the service that needs to be executed
	Service string `json:"service"`
}

// ClaimList List of all claims
type ClaimList = []Claim

// Error The error that occured while processing this request.
type Error struct {
	Message string `json:"message"`
}

// Evaluate Evaluate.
type Evaluate struct {
	// Approved only use approved claims, default to true
	Approved *bool `json:"approved,omitempty"`

	// Date Can be used to overwrite the date used by the service
	Date  *openapi_types.Date                `json:"date,omitempty"`
	Input *map[string]map[string]interface{} `json:"input,omitempty"`

	// Law Specify the law that needs to be executed
	Law string `json:"law"`

	// Output specify a requested output value
	Output     *string                 `json:"output,omitempty"`
	Parameters *map[string]interface{} `json:"parameters,omitempty"`

	// Service Specify the service that needs to be executed
	Service string `json:"service"`
}

// EvaluateResponseSchema Evaluate response
type EvaluateResponseSchema struct {
	Input map[string]interface{} `json:"input"`

	// MissingRequired Will be true when a required value is missing
	MissingRequired bool                   `json:"missingRequired"`
	Output          map[string]interface{} `json:"output"`

	// Path path node
	Path PathNode `json:"path"`

	// RequirementsMet Will be true when all requirements where met
	RequirementsMet bool `json:"requirementsMet"`

	// RulespecId Identifier of the rulespec
	RulespecId openapi_types.UUID `json:"rulespecId"`
}

// Law Law
type Law struct {
	// DiscoverableBy Who can discover this law
	DiscoverableBy []string `json:"discoverable_by"`

	// Name Name of the law
	Name string `json:"name"`
}

// PathNode path node
type PathNode struct {
	Children    *[]PathNode             `json:"children,omitempty"`
	Details     *map[string]interface{} `json:"details,omitempty"`
	Name        string                  `json:"name"`
	Required    *bool                   `json:"required,omitempty"`
	ResolveType *string                 `json:"resolveType,omitempty"`
	Result      *interface{}            `json:"result,omitempty"`
	Type        string                  `json:"type"`
}

// Profile Profile
type Profile struct {
	// Bsn Burgerservicenummer of a Dutch citizen
	Bsn Bsn `json:"bsn"`

	// Description Description of the burger
	Description string `json:"description"`

	// Name Name of the burger
	Name string `json:"name"`

	// Sources All sources for a certain profile
	Sources map[string]Source `json:"sources"`
}

// ProfileList List of all burgers
type ProfileList = []Profile

// RuleSpec Rule spec
type RuleSpec map[string]interface{}

// Service Service
type Service struct {
	Laws []Law `json:"laws"`

	// Name Service name
	Name string `json:"name"`
}

// ServiceList List of all services
type ServiceList = []Service

// Source A source
type Source map[string][]map[string]interface{}

// Bsn Burgerservicenummer of a Dutch citizen
type Bsn = string

// DiscoverableBy DiscoverableBy is a string that can be used to filter lists
type DiscoverableBy = string

// ReferenceDate reference date
type ReferenceDate = openapi_types.Date

// PathBSN Burgerservicenummer of a Dutch citizen
type PathBSN = Bsn

// PathLaw defines model for pathLaw.
type PathLaw = string

// PathService defines model for pathService.
type PathService = string

// QueryDiscoverableBy DiscoverableBy is a string that can be used to filter lists
type QueryDiscoverableBy = DiscoverableBy

// QueryIncludeRejected defines model for queryIncludeRejected.
type QueryIncludeRejected = bool

// QueryLaw defines model for queryLaw.
type QueryLaw = string

// QueryOnlyApproved defines model for queryOnlyApproved.
type QueryOnlyApproved = bool

// QueryReferenceDate reference date
type QueryReferenceDate = ReferenceDate

// QueryService defines model for queryService.
type QueryService = string

// BadRequestErrorResponse defines model for BadRequestErrorResponse.
type BadRequestErrorResponse struct {
	Errors []Error `json:"errors"`
}

// CaseListResponse defines model for CaseListResponse.
type CaseListResponse struct {
	// Data List of all cases
	Data CaseList `json:"data"`
}

// CaseResponse defines model for CaseResponse.
type CaseResponse struct {
	// Data Claim
	Data Case `json:"data"`
}

// ClaimListResponse defines model for ClaimListResponse.
type ClaimListResponse struct {
	// Data List of all claims
	Data ClaimList `json:"data"`
}

// ClaimListWithKeyResponse defines model for ClaimListWithKeyResponse.
type ClaimListWithKeyResponse struct {
	Data map[string]Claim `json:"data"`
}

// EvaluateResponse defines model for EvaluateResponse.
type EvaluateResponse struct {
	// Data Evaluate response
	Data EvaluateResponseSchema `json:"data"`
}

// InternalServerErrorResponse defines model for InternalServerErrorResponse.
type InternalServerErrorResponse struct {
	Errors []Error `json:"errors"`
}

// ProfileListResponse defines model for ProfileListResponse.
type ProfileListResponse struct {
	// Data List of all burgers
	Data ProfileList `json:"data"`
}

// ProfileResponse defines model for ProfileResponse.
type ProfileResponse struct {
	// Data Profile
	Data Profile `json:"data"`
}

// ResourceNotFoundErrorResponse defines model for ResourceNotFoundErrorResponse.
type ResourceNotFoundErrorResponse struct {
	Errors *[]Error `json:"errors,omitempty"`
}

// RuleSpecResponse defines model for RuleSpecResponse.
type RuleSpecResponse struct {
	// Data Rule spec
	Data RuleSpec `json:"data"`
}

// ServiceListResponse defines model for ServiceListResponse.
type ServiceListResponse struct {
	// Data List of all services
	Data ServiceList `json:"data"`
}

// EvaluateRequest defines model for EvaluateRequest.
type EvaluateRequest struct {
	// Data Evaluate.
	Data Evaluate `json:"data"`
}

// GetClaimsBsnParams defines parameters for GetClaimsBsn.
type GetClaimsBsnParams struct {
	// Approved If added to URI only approved claims will be returned.
	Approved *QueryOnlyApproved `form:"approved,omitempty" json:"approved,omitempty"`

	// IncludeRejected If added to URI rejected claims will be added to the return
	IncludeRejected *QueryIncludeRejected `form:"include_rejected,omitempty" json:"include_rejected,omitempty"`
}

// GetClaimsBsnServiceLawParams defines parameters for GetClaimsBsnServiceLaw.
type GetClaimsBsnServiceLawParams struct {
	// Approved If added to URI only approved claims will be returned.
	Approved *QueryOnlyApproved `form:"approved,omitempty" json:"approved,omitempty"`

	// IncludeRejected If added to URI rejected claims will be added to the return
	IncludeRejected *QueryIncludeRejected `form:"include_rejected,omitempty" json:"include_rejected,omitempty"`
}

// ServiceLawsDiscoverableListParams defines parameters for ServiceLawsDiscoverableList.
type ServiceLawsDiscoverableListParams struct {
	// DiscoverableBy Filter for discoverable by, defaults to 'CITIZEN'
	DiscoverableBy *QueryDiscoverableBy `form:"discoverableBy,omitempty" json:"discoverableBy,omitempty"`
}

// EvaluateJSONBody defines parameters for Evaluate.
type EvaluateJSONBody struct {
	// Data Evaluate.
	Data Evaluate `json:"data"`
}

// RuleSpecGetParams defines parameters for RuleSpecGet.
type RuleSpecGetParams struct {
	// Service filter for service
	Service QueryService `form:"service" json:"service"`

	// Law filter for law
	Law QueryLaw `form:"law" json:"law"`

	// ReferenceDate reference date
	ReferenceDate QueryReferenceDate `form:"reference_date" json:"reference_date"`
}

// EvaluateJSONRequestBody defines body for Evaluate for application/json ContentType.
type EvaluateJSONRequestBody EvaluateJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /cases/{bsn}/{service}/{law})
	GetCasesBsnServiceLaw(w http.ResponseWriter, r *http.Request, bsn PathBSN, service PathService, law PathLaw)

	// (GET /cases/{service}/{law})
	GetCasesServiceLaw(w http.ResponseWriter, r *http.Request, service PathService, law PathLaw)

	// (GET /claims/{bsn})
	GetClaimsBsn(w http.ResponseWriter, r *http.Request, bsn PathBSN, params GetClaimsBsnParams)

	// (GET /claims/{bsn}/{service}/{law})
	GetClaimsBsnServiceLaw(w http.ResponseWriter, r *http.Request, bsn PathBSN, service PathService, law PathLaw, params GetClaimsBsnServiceLawParams)

	// (GET /discoverable-service-laws)
	ServiceLawsDiscoverableList(w http.ResponseWriter, r *http.Request, params ServiceLawsDiscoverableListParams)

	// (POST /evaluate)
	Evaluate(w http.ResponseWriter, r *http.Request)

	// (GET /profiles)
	ProfileList(w http.ResponseWriter, r *http.Request)

	// (GET /profiles/{bsn})
	ProfileGet(w http.ResponseWriter, r *http.Request, bsn PathBSN)

	// (GET /rule-spec)
	RuleSpecGet(w http.ResponseWriter, r *http.Request, params RuleSpecGetParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /cases/{bsn}/{service}/{law})
func (_ Unimplemented) GetCasesBsnServiceLaw(w http.ResponseWriter, r *http.Request, bsn PathBSN, service PathService, law PathLaw) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /cases/{service}/{law})
func (_ Unimplemented) GetCasesServiceLaw(w http.ResponseWriter, r *http.Request, service PathService, law PathLaw) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /claims/{bsn})
func (_ Unimplemented) GetClaimsBsn(w http.ResponseWriter, r *http.Request, bsn PathBSN, params GetClaimsBsnParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /claims/{bsn}/{service}/{law})
func (_ Unimplemented) GetClaimsBsnServiceLaw(w http.ResponseWriter, r *http.Request, bsn PathBSN, service PathService, law PathLaw, params GetClaimsBsnServiceLawParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /discoverable-service-laws)
func (_ Unimplemented) ServiceLawsDiscoverableList(w http.ResponseWriter, r *http.Request, params ServiceLawsDiscoverableListParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /evaluate)
func (_ Unimplemented) Evaluate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /profiles)
func (_ Unimplemented) ProfileList(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /profiles/{bsn})
func (_ Unimplemented) ProfileGet(w http.ResponseWriter, r *http.Request, bsn PathBSN) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /rule-spec)
func (_ Unimplemented) RuleSpecGet(w http.ResponseWriter, r *http.Request, params RuleSpecGetParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetCasesBsnServiceLaw operation middleware
func (siw *ServerInterfaceWrapper) GetCasesBsnServiceLaw(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "bsn" -------------
	var bsn PathBSN

	err = runtime.BindStyledParameterWithOptions("simple", "bsn", chi.URLParam(r, "bsn"), &bsn, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bsn", Err: err})
		return
	}

	// ------------- Path parameter "service" -------------
	var service PathService

	err = runtime.BindStyledParameterWithOptions("simple", "service", chi.URLParam(r, "service"), &service, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "service", Err: err})
		return
	}

	// ------------- Path parameter "law" -------------
	var law PathLaw

	err = runtime.BindStyledParameterWithOptions("simple", "law", chi.URLParam(r, "law"), &law, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "law", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCasesBsnServiceLaw(w, r, bsn, service, law)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCasesServiceLaw operation middleware
func (siw *ServerInterfaceWrapper) GetCasesServiceLaw(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "service" -------------
	var service PathService

	err = runtime.BindStyledParameterWithOptions("simple", "service", chi.URLParam(r, "service"), &service, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "service", Err: err})
		return
	}

	// ------------- Path parameter "law" -------------
	var law PathLaw

	err = runtime.BindStyledParameterWithOptions("simple", "law", chi.URLParam(r, "law"), &law, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "law", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCasesServiceLaw(w, r, service, law)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetClaimsBsn operation middleware
func (siw *ServerInterfaceWrapper) GetClaimsBsn(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "bsn" -------------
	var bsn PathBSN

	err = runtime.BindStyledParameterWithOptions("simple", "bsn", chi.URLParam(r, "bsn"), &bsn, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bsn", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetClaimsBsnParams

	// ------------- Optional query parameter "approved" -------------

	err = runtime.BindQueryParameter("form", true, false, "approved", r.URL.Query(), &params.Approved)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "approved", Err: err})
		return
	}

	// ------------- Optional query parameter "include_rejected" -------------

	err = runtime.BindQueryParameter("form", true, false, "include_rejected", r.URL.Query(), &params.IncludeRejected)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_rejected", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetClaimsBsn(w, r, bsn, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetClaimsBsnServiceLaw operation middleware
func (siw *ServerInterfaceWrapper) GetClaimsBsnServiceLaw(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "bsn" -------------
	var bsn PathBSN

	err = runtime.BindStyledParameterWithOptions("simple", "bsn", chi.URLParam(r, "bsn"), &bsn, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bsn", Err: err})
		return
	}

	// ------------- Path parameter "service" -------------
	var service PathService

	err = runtime.BindStyledParameterWithOptions("simple", "service", chi.URLParam(r, "service"), &service, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "service", Err: err})
		return
	}

	// ------------- Path parameter "law" -------------
	var law PathLaw

	err = runtime.BindStyledParameterWithOptions("simple", "law", chi.URLParam(r, "law"), &law, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "law", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetClaimsBsnServiceLawParams

	// ------------- Optional query parameter "approved" -------------

	err = runtime.BindQueryParameter("form", true, false, "approved", r.URL.Query(), &params.Approved)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "approved", Err: err})
		return
	}

	// ------------- Optional query parameter "include_rejected" -------------

	err = runtime.BindQueryParameter("form", true, false, "include_rejected", r.URL.Query(), &params.IncludeRejected)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_rejected", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetClaimsBsnServiceLaw(w, r, bsn, service, law, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ServiceLawsDiscoverableList operation middleware
func (siw *ServerInterfaceWrapper) ServiceLawsDiscoverableList(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ServiceLawsDiscoverableListParams

	// ------------- Optional query parameter "discoverableBy" -------------

	err = runtime.BindQueryParameter("form", true, false, "discoverableBy", r.URL.Query(), &params.DiscoverableBy)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "discoverableBy", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ServiceLawsDiscoverableList(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Evaluate operation middleware
func (siw *ServerInterfaceWrapper) Evaluate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Evaluate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ProfileList operation middleware
func (siw *ServerInterfaceWrapper) ProfileList(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ProfileList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ProfileGet operation middleware
func (siw *ServerInterfaceWrapper) ProfileGet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "bsn" -------------
	var bsn PathBSN

	err = runtime.BindStyledParameterWithOptions("simple", "bsn", chi.URLParam(r, "bsn"), &bsn, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bsn", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ProfileGet(w, r, bsn)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RuleSpecGet operation middleware
func (siw *ServerInterfaceWrapper) RuleSpecGet(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params RuleSpecGetParams

	// ------------- Required query parameter "service" -------------

	if paramValue := r.URL.Query().Get("service"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "service"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "service", r.URL.Query(), &params.Service)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "service", Err: err})
		return
	}

	// ------------- Required query parameter "law" -------------

	if paramValue := r.URL.Query().Get("law"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "law"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "law", r.URL.Query(), &params.Law)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "law", Err: err})
		return
	}

	// ------------- Required query parameter "reference_date" -------------

	if paramValue := r.URL.Query().Get("reference_date"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "reference_date"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "reference_date", r.URL.Query(), &params.ReferenceDate)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "reference_date", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RuleSpecGet(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cases/{bsn}/{service}/{law}", wrapper.GetCasesBsnServiceLaw)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cases/{service}/{law}", wrapper.GetCasesServiceLaw)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/claims/{bsn}", wrapper.GetClaimsBsn)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/claims/{bsn}/{service}/{law}", wrapper.GetClaimsBsnServiceLaw)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/discoverable-service-laws", wrapper.ServiceLawsDiscoverableList)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/evaluate", wrapper.Evaluate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/profiles", wrapper.ProfileList)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/profiles/{bsn}", wrapper.ProfileGet)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/rule-spec", wrapper.RuleSpecGet)
	})

	return r
}

type BadRequestErrorResponseJSONResponse struct {
	Errors []Error `json:"errors"`
}

type CaseListResponseJSONResponse struct {
	// Data List of all cases
	Data CaseList `json:"data"`
}

type CaseResponseJSONResponse struct {
	// Data Claim
	Data Case `json:"data"`
}

type ClaimListResponseJSONResponse struct {
	// Data List of all claims
	Data ClaimList `json:"data"`
}

type ClaimListWithKeyResponseJSONResponse struct {
	Data map[string]Claim `json:"data"`
}

type EvaluateResponseJSONResponse struct {
	// Data Evaluate response
	Data EvaluateResponseSchema `json:"data"`
}

type InternalServerErrorResponseJSONResponse struct {
	Errors []Error `json:"errors"`
}

type ProfileListResponseJSONResponse struct {
	// Data List of all burgers
	Data ProfileList `json:"data"`
}

type ProfileResponseJSONResponse struct {
	// Data Profile
	Data Profile `json:"data"`
}

type ResourceNotFoundErrorResponseJSONResponse struct {
	Errors *[]Error `json:"errors,omitempty"`
}

type RuleSpecResponseJSONResponse struct {
	// Data Rule spec
	Data RuleSpec `json:"data"`
}

type ServiceListResponseJSONResponse struct {
	// Data List of all services
	Data ServiceList `json:"data"`
}

type GetCasesBsnServiceLawRequestObject struct {
	Bsn     PathBSN     `json:"bsn"`
	Service PathService `json:"service"`
	Law     PathLaw     `json:"law"`
}

type GetCasesBsnServiceLawResponseObject interface {
	VisitGetCasesBsnServiceLawResponse(w http.ResponseWriter) error
}

type GetCasesBsnServiceLaw200JSONResponse struct{ CaseResponseJSONResponse }

func (response GetCasesBsnServiceLaw200JSONResponse) VisitGetCasesBsnServiceLawResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCasesBsnServiceLaw400JSONResponse struct {
	BadRequestErrorResponseJSONResponse
}

func (response GetCasesBsnServiceLaw400JSONResponse) VisitGetCasesBsnServiceLawResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetCasesBsnServiceLaw404JSONResponse struct {
	ResourceNotFoundErrorResponseJSONResponse
}

func (response GetCasesBsnServiceLaw404JSONResponse) VisitGetCasesBsnServiceLawResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetCasesBsnServiceLaw500JSONResponse struct {
	InternalServerErrorResponseJSONResponse
}

func (response GetCasesBsnServiceLaw500JSONResponse) VisitGetCasesBsnServiceLawResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetCasesServiceLawRequestObject struct {
	Service PathService `json:"service"`
	Law     PathLaw     `json:"law"`
}

type GetCasesServiceLawResponseObject interface {
	VisitGetCasesServiceLawResponse(w http.ResponseWriter) error
}

type GetCasesServiceLaw200JSONResponse struct{ CaseListResponseJSONResponse }

func (response GetCasesServiceLaw200JSONResponse) VisitGetCasesServiceLawResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCasesServiceLaw400JSONResponse struct {
	BadRequestErrorResponseJSONResponse
}

func (response GetCasesServiceLaw400JSONResponse) VisitGetCasesServiceLawResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetCasesServiceLaw500JSONResponse struct {
	InternalServerErrorResponseJSONResponse
}

func (response GetCasesServiceLaw500JSONResponse) VisitGetCasesServiceLawResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetClaimsBsnRequestObject struct {
	Bsn    PathBSN `json:"bsn"`
	Params GetClaimsBsnParams
}

type GetClaimsBsnResponseObject interface {
	VisitGetClaimsBsnResponse(w http.ResponseWriter) error
}

type GetClaimsBsn200JSONResponse struct{ ClaimListResponseJSONResponse }

func (response GetClaimsBsn200JSONResponse) VisitGetClaimsBsnResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetClaimsBsn400JSONResponse struct {
	BadRequestErrorResponseJSONResponse
}

func (response GetClaimsBsn400JSONResponse) VisitGetClaimsBsnResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetClaimsBsn500JSONResponse struct {
	InternalServerErrorResponseJSONResponse
}

func (response GetClaimsBsn500JSONResponse) VisitGetClaimsBsnResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetClaimsBsnServiceLawRequestObject struct {
	Bsn     PathBSN     `json:"bsn"`
	Service PathService `json:"service"`
	Law     PathLaw     `json:"law"`
	Params  GetClaimsBsnServiceLawParams
}

type GetClaimsBsnServiceLawResponseObject interface {
	VisitGetClaimsBsnServiceLawResponse(w http.ResponseWriter) error
}

type GetClaimsBsnServiceLaw200JSONResponse struct {
	ClaimListWithKeyResponseJSONResponse
}

func (response GetClaimsBsnServiceLaw200JSONResponse) VisitGetClaimsBsnServiceLawResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetClaimsBsnServiceLaw400JSONResponse struct {
	BadRequestErrorResponseJSONResponse
}

func (response GetClaimsBsnServiceLaw400JSONResponse) VisitGetClaimsBsnServiceLawResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetClaimsBsnServiceLaw500JSONResponse struct {
	InternalServerErrorResponseJSONResponse
}

func (response GetClaimsBsnServiceLaw500JSONResponse) VisitGetClaimsBsnServiceLawResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ServiceLawsDiscoverableListRequestObject struct {
	Params ServiceLawsDiscoverableListParams
}

type ServiceLawsDiscoverableListResponseObject interface {
	VisitServiceLawsDiscoverableListResponse(w http.ResponseWriter) error
}

type ServiceLawsDiscoverableList200JSONResponse struct {
	ServiceListResponseJSONResponse
}

func (response ServiceLawsDiscoverableList200JSONResponse) VisitServiceLawsDiscoverableListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ServiceLawsDiscoverableList400JSONResponse struct {
	BadRequestErrorResponseJSONResponse
}

func (response ServiceLawsDiscoverableList400JSONResponse) VisitServiceLawsDiscoverableListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ServiceLawsDiscoverableList500JSONResponse struct {
	InternalServerErrorResponseJSONResponse
}

func (response ServiceLawsDiscoverableList500JSONResponse) VisitServiceLawsDiscoverableListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type EvaluateRequestObject struct {
	Body *EvaluateJSONRequestBody
}

type EvaluateResponseObject interface {
	VisitEvaluateResponse(w http.ResponseWriter) error
}

type Evaluate200JSONResponse struct{ EvaluateResponseJSONResponse }

func (response Evaluate200JSONResponse) VisitEvaluateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Evaluate400JSONResponse struct {
	BadRequestErrorResponseJSONResponse
}

func (response Evaluate400JSONResponse) VisitEvaluateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Evaluate500JSONResponse struct {
	InternalServerErrorResponseJSONResponse
}

func (response Evaluate500JSONResponse) VisitEvaluateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ProfileListRequestObject struct {
}

type ProfileListResponseObject interface {
	VisitProfileListResponse(w http.ResponseWriter) error
}

type ProfileList200JSONResponse struct {
	ProfileListResponseJSONResponse
}

func (response ProfileList200JSONResponse) VisitProfileListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ProfileList400JSONResponse struct {
	BadRequestErrorResponseJSONResponse
}

func (response ProfileList400JSONResponse) VisitProfileListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ProfileList500JSONResponse struct {
	InternalServerErrorResponseJSONResponse
}

func (response ProfileList500JSONResponse) VisitProfileListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ProfileGetRequestObject struct {
	Bsn PathBSN `json:"bsn"`
}

type ProfileGetResponseObject interface {
	VisitProfileGetResponse(w http.ResponseWriter) error
}

type ProfileGet200JSONResponse struct{ ProfileResponseJSONResponse }

func (response ProfileGet200JSONResponse) VisitProfileGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ProfileGet400JSONResponse struct {
	BadRequestErrorResponseJSONResponse
}

func (response ProfileGet400JSONResponse) VisitProfileGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ProfileGet404JSONResponse struct {
	ResourceNotFoundErrorResponseJSONResponse
}

func (response ProfileGet404JSONResponse) VisitProfileGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ProfileGet500JSONResponse struct {
	InternalServerErrorResponseJSONResponse
}

func (response ProfileGet500JSONResponse) VisitProfileGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RuleSpecGetRequestObject struct {
	Params RuleSpecGetParams
}

type RuleSpecGetResponseObject interface {
	VisitRuleSpecGetResponse(w http.ResponseWriter) error
}

type RuleSpecGet200JSONResponse struct{ RuleSpecResponseJSONResponse }

func (response RuleSpecGet200JSONResponse) VisitRuleSpecGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RuleSpecGet400JSONResponse struct {
	BadRequestErrorResponseJSONResponse
}

func (response RuleSpecGet400JSONResponse) VisitRuleSpecGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RuleSpecGet500JSONResponse struct {
	InternalServerErrorResponseJSONResponse
}

func (response RuleSpecGet500JSONResponse) VisitRuleSpecGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /cases/{bsn}/{service}/{law})
	GetCasesBsnServiceLaw(ctx context.Context, request GetCasesBsnServiceLawRequestObject) (GetCasesBsnServiceLawResponseObject, error)

	// (GET /cases/{service}/{law})
	GetCasesServiceLaw(ctx context.Context, request GetCasesServiceLawRequestObject) (GetCasesServiceLawResponseObject, error)

	// (GET /claims/{bsn})
	GetClaimsBsn(ctx context.Context, request GetClaimsBsnRequestObject) (GetClaimsBsnResponseObject, error)

	// (GET /claims/{bsn}/{service}/{law})
	GetClaimsBsnServiceLaw(ctx context.Context, request GetClaimsBsnServiceLawRequestObject) (GetClaimsBsnServiceLawResponseObject, error)

	// (GET /discoverable-service-laws)
	ServiceLawsDiscoverableList(ctx context.Context, request ServiceLawsDiscoverableListRequestObject) (ServiceLawsDiscoverableListResponseObject, error)

	// (POST /evaluate)
	Evaluate(ctx context.Context, request EvaluateRequestObject) (EvaluateResponseObject, error)

	// (GET /profiles)
	ProfileList(ctx context.Context, request ProfileListRequestObject) (ProfileListResponseObject, error)

	// (GET /profiles/{bsn})
	ProfileGet(ctx context.Context, request ProfileGetRequestObject) (ProfileGetResponseObject, error)

	// (GET /rule-spec)
	RuleSpecGet(ctx context.Context, request RuleSpecGetRequestObject) (RuleSpecGetResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetCasesBsnServiceLaw operation middleware
func (sh *strictHandler) GetCasesBsnServiceLaw(w http.ResponseWriter, r *http.Request, bsn PathBSN, service PathService, law PathLaw) {
	var request GetCasesBsnServiceLawRequestObject

	request.Bsn = bsn
	request.Service = service
	request.Law = law

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCasesBsnServiceLaw(ctx, request.(GetCasesBsnServiceLawRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCasesBsnServiceLaw")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCasesBsnServiceLawResponseObject); ok {
		if err := validResponse.VisitGetCasesBsnServiceLawResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCasesServiceLaw operation middleware
func (sh *strictHandler) GetCasesServiceLaw(w http.ResponseWriter, r *http.Request, service PathService, law PathLaw) {
	var request GetCasesServiceLawRequestObject

	request.Service = service
	request.Law = law

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCasesServiceLaw(ctx, request.(GetCasesServiceLawRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCasesServiceLaw")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCasesServiceLawResponseObject); ok {
		if err := validResponse.VisitGetCasesServiceLawResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetClaimsBsn operation middleware
func (sh *strictHandler) GetClaimsBsn(w http.ResponseWriter, r *http.Request, bsn PathBSN, params GetClaimsBsnParams) {
	var request GetClaimsBsnRequestObject

	request.Bsn = bsn
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetClaimsBsn(ctx, request.(GetClaimsBsnRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetClaimsBsn")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetClaimsBsnResponseObject); ok {
		if err := validResponse.VisitGetClaimsBsnResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetClaimsBsnServiceLaw operation middleware
func (sh *strictHandler) GetClaimsBsnServiceLaw(w http.ResponseWriter, r *http.Request, bsn PathBSN, service PathService, law PathLaw, params GetClaimsBsnServiceLawParams) {
	var request GetClaimsBsnServiceLawRequestObject

	request.Bsn = bsn
	request.Service = service
	request.Law = law
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetClaimsBsnServiceLaw(ctx, request.(GetClaimsBsnServiceLawRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetClaimsBsnServiceLaw")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetClaimsBsnServiceLawResponseObject); ok {
		if err := validResponse.VisitGetClaimsBsnServiceLawResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ServiceLawsDiscoverableList operation middleware
func (sh *strictHandler) ServiceLawsDiscoverableList(w http.ResponseWriter, r *http.Request, params ServiceLawsDiscoverableListParams) {
	var request ServiceLawsDiscoverableListRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ServiceLawsDiscoverableList(ctx, request.(ServiceLawsDiscoverableListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ServiceLawsDiscoverableList")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ServiceLawsDiscoverableListResponseObject); ok {
		if err := validResponse.VisitServiceLawsDiscoverableListResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Evaluate operation middleware
func (sh *strictHandler) Evaluate(w http.ResponseWriter, r *http.Request) {
	var request EvaluateRequestObject

	var body EvaluateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Evaluate(ctx, request.(EvaluateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Evaluate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(EvaluateResponseObject); ok {
		if err := validResponse.VisitEvaluateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ProfileList operation middleware
func (sh *strictHandler) ProfileList(w http.ResponseWriter, r *http.Request) {
	var request ProfileListRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ProfileList(ctx, request.(ProfileListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ProfileList")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ProfileListResponseObject); ok {
		if err := validResponse.VisitProfileListResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ProfileGet operation middleware
func (sh *strictHandler) ProfileGet(w http.ResponseWriter, r *http.Request, bsn PathBSN) {
	var request ProfileGetRequestObject

	request.Bsn = bsn

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ProfileGet(ctx, request.(ProfileGetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ProfileGet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ProfileGetResponseObject); ok {
		if err := validResponse.VisitProfileGetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RuleSpecGet operation middleware
func (sh *strictHandler) RuleSpecGet(w http.ResponseWriter, r *http.Request, params RuleSpecGetParams) {
	var request RuleSpecGetRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RuleSpecGet(ctx, request.(RuleSpecGetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RuleSpecGet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RuleSpecGetResponseObject); ok {
		if err := validResponse.VisitRuleSpecGetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xb3W8jtxH/Vwg2QF72LNuXFIjeTrZyUOvoAsvpAb26BrU7sphQ5IbkWlEE/e8Fv/Zb",
	"0mrtGE7bN2tJDmd+88GZIb3FsVilggPXCg+3OCWSrECD9L/0cjSbmj8TULGkqaaC4yEeZfIRpAL5RGPg",
	"2WoFEokFIug60/ESxVTT34HjCFMz25DBEeZkBXiI58oMSPg1oxISPNQygwireAkrYnb6SsICD/FfBgVn",
	"AzeqBmbtbhdZijdk3WRsQZkGiRZCIkbW7Qy4gf0MwG9klTIz83chH7UAxcjjGjSOsN6k5rvSkvLHnJOZ",
	"w+EgNx6rdo6KwS5c3X0az24+fBxPWxn6NQO5uaYqFk8gyZzBaNNk7PuCsaQ0Fc03EUpgQTKmFdICfX01",
	"uZv8czz9OvBtqReMJ9V9uqqxtixne8JjliVwCz9DrA0Idb4nC0SSBBLD20+3EyT9TBQzQlcKrSljaA7F",
	"JL0EJEFnku+RgLotHwIl3Ir5gjAFOdpzIRgQXvB9ginWtn9RW7S0P3G2+ZCmUjx1AVBwtkHET6+j6ICD",
	"5GwP82FdO2ZOlH2Q3cICJPAYrolu8RwZhlFixtv3zyc9+En9goqssJJz2MOra/y9nFvvHAlQeiQSCjY4",
	"j58Iy4iGWzdgPsWCa+D2T5KmjMbEsDz4WRm+t6VdUylSkNpTSog+ClLYDQdenDhf3OL7nGUxN37kWK7C",
	"9gEpnSXANXqUhGvkZqIsNcpDXryzBlhuP5UKrhy3I5J4kcdSCnnrx06SP0d9i8EQUXj4ZYtXoBR5NFIs",
	"hEBrw+paCqOAexPpK5iFZSVahylEmGpYqaM4G7p4l+NJpCSbBuh+9y6wT/gTYTRBlKeZRiozuBiX3kX4",
	"iii4oUr3gvB0Ewrb9TchQwExqjQKFhHEeEURnsl+hXMTb19TA2G/Z8hgSLToIFD+TPXy77B5QYFIklCz",
	"gLAfK+NHBS15US5PT6lnWRyDUouMsQ1y8T8/Ls02RSx+FT3Wt5s5Wr3FC/QqKp1wDZITZs5BkP+PtZ1i",
	"rYPM5gUgkV1qQ+2PUiwoe81oW9qxv2F4Ik1/9wOvK8vz5SiLcAtKZDKGqdDfi4wn/1sWfhSyAA/iQqOF",
	"Acga8m3GYJZC/EqaD9v1V72hgFQKcUX5Prl/RX8s7dhfmBuyrvviLlQTlhOboDQqFncc1o2OlKrEepkW",
	"2TZNl25MZGvYxpZGaXSxsQU4I2ukl0QjDpDYvsIcEPwGceYK7lq1E+WF00GqftKJlDXRmXM0nq0M9rOf",
	"Rj9M7u7G1zjC1+OrybX9azJ9uB3/YzL+jCP8afS38ZWZcN9WdJf16FpbRdnnqnu/Z1O/RQbelNR8tS01",
	"xlBMTOnT0eVdilr3eJ+hdTWN7sr/BTYl+ymA/vMYRScdGjFbFZhn1Ic16DLFriqsZa+5Dl04b+x0twSX",
	"ajixRRxnJj1dL82Rl0phUlfKH5FeUlUutKs6z0+bclOidvAcAy/QaIMq7yA0+A8jhqfSWWpNqNn3yu2g",
	"1DHZHYpt1c1sxytTUO965Y1P2zaUGeCoJSomrQJcEW5sLFOusSaeQK4l1WBN0rY37NC8YqNlYfHl+eW3",
	"784v3r2/wBFeCLkiGg+xb2s1XMHW8odqo/bvlY5coZjGh5f3XZFpz3GVqPJESTBLSJCbi4xNtApfvaI4",
	"SdJXCiHV4HHIF2oF3F7PKM77uqEfMYU9QKyojQi3OdP1jT/7FrBZj9ZL4F5FZrZTDaIKeTKtnlKo/CTO",
	"7MXIsXKA6OVUJPaY80ytzIQfQHeShDFUXma+SkCrcle9JIjMGBg7nbS10xPgmi6ou/6ylw1+dtmNs4we",
	"NxqPV3DupmQVTpoq9NC1WVvr9cSNPddK4bZ8KfMw3xie/O2PIepb2mvQD5T/IlZKA58DI0oHt6xmxHVi",
	"DbUsBYoJz6+f3OHkL0rCIdnw/fqB6Liq056SFQR9OIqHobdUogbPbVDmptfY1KCPuBmqYxEvKUsk2Iyq",
	"0/lftu+6xAloQtnpoS8g1YBUlmJAi/GDEuwJ7uxA62qVMeN1OavbI2DbUc9PK8K+1m8AHAb656oVenXy",
	"18WvYDtze8vddgYdt7v9a11Zrfq2Nmd2OW5erzCGPGl7NUVQDFITyk0G6IE73A11mW9whhLxgucDCjue",
	"BDtIOmfBedOn6QR5V+CIF+zpBOAWKfbe9s2a2ZpNTV2T51lBs5gxGt98mN1Nph+vJ+Pp7K4ZT92GHeOH",
	"Ce2dg6WXD3m9d4qUlpv7/SgetwWfInU2hqCFFrG8Qxxwp3yHPmlxKfLWbjPdvi0rfUTq+WSmKAouLi4u",
	"Ly/fv3/vDncN0hD695fzd9/db7/bfdUWXZIjLz+qL0NMEkeQW+0S3rhayvi7bkaVVhXegpVHbWfCaVf7",
	"/aqgna2DFsKeOFTb9TdkjYhCV+4UfgKp3JbnZ+dnFzYpTYGTlOIhfn92fuZxXVrbGNguy2A7V3w32Ho9",
	"7QZbRtY7M/7Yllx+BG0CLVGA5sRAJjiaKx7lRQThiU9BjL0Rv8wsMNM/8dFs6k37A09uqhNNwml2uDKM",
	"jRQPzmVnlaugL+2+U0wZhIdcu6jT1MLbOk238ea+dk1/eX6+z6nzeYPK1e0uwt90WbTvAYBd/83x9Ycb",
	"/7sIf9uFi0PXY7bBTh6VPQ6IAnxvvgQLO8W2QvevMK8Xt6xnmtWr2kqlX/8C9vKHadq2lFwwOa7g0Bys",
	"KDI0Fke5Ols1aNeObOb2h4WE5ruyrovqD/p6ar7xTOLNqd52bJu6P93ZX8IW3vZB8Seyt/pjlrdsduXE",
	"7523unehbDhoc5UXwOF4+Vd2fn75V2QJ1G2tsC9VTidt1n+qwbU9V+6ntbYr3bemMOMATl1Qug1JRVu5",
	"lPd+izZWVQ35hUr5cehmP7Ol96OD+uPRXR/EG6+e3i7cvgdy3BnyiXW0y22OPmC1vQB6a3iFlksVs45p",
	"zDHkPoLufxzdPwPy//ICo6o0mZnw73tje/UlS62wqrJCa62PtirP5rse2afkBNV/GuhnFI0HTG80aPnr",
	"ygB9Jhke4qXWqRoOBiSlZ270TIPSg6cLi4YnsQ1txYCt/1l0VPNP4alB8cE+H7nf/ScAAP//nkS+bxk2",
	"AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
