// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Error The error that occured while processing this request.
type Error struct {
	Message string `json:"message"`
}

// Evaluate Evaluate.
type Evaluate struct {
	// Approved only use approved claims, default to true
	Approved *bool `json:"approved,omitempty"`

	// Date Can be used to overwrite the date used by the service
	Date  *openapi_types.Date                `json:"date,omitempty"`
	Input *map[string]map[string]interface{} `json:"input,omitempty"`

	// Law Specify the law that needs to be executed
	Law string `json:"law"`

	// Output specify a requested output value
	Output     *string                 `json:"output,omitempty"`
	Parameters *map[string]interface{} `json:"parameters,omitempty"`

	// Service Specify the service that needs to be executed
	Service string `json:"service"`
}

// EvaluateResponseSchema Evaluate response
type EvaluateResponseSchema struct {
	Input map[string]interface{} `json:"input"`

	// MissingRequired Will be true when a required value is missing
	MissingRequired bool                   `json:"missingRequired"`
	Output          map[string]interface{} `json:"output"`

	// RequirementsMet Will be true when all requirements where met
	RequirementsMet bool `json:"requirementsMet"`

	// RulespecId Identifier of the rulespec
	RulespecId openapi_types.UUID `json:"rulespecId"`
}

// Law Law
type Law struct {
	// DiscoverableBy Who can discover this law
	DiscoverableBy []string `json:"discoverable_by"`

	// Name Name of the law
	Name string `json:"name"`
}

// Profile Profile
type Profile struct {
	// Bsn Burgerservicenummer of a Dutch citizen
	Bsn Bsn `json:"bsn"`

	// Description Description of the burger
	Description string `json:"description"`

	// Name Name of the burger
	Name string `json:"name"`

	// Sources All sources for a certain profile
	Sources map[string]Source `json:"sources"`
}

// ProfileList List of all burgers
type ProfileList = []Profile

// RuleSpec Rule spec
type RuleSpec map[string]interface{}

// Service Service
type Service struct {
	Laws []Law `json:"laws"`

	// Name Service name
	Name string `json:"name"`
}

// ServiceList List of all services
type ServiceList = []Service

// Source A source
type Source map[string][]map[string]interface{}

// Bsn Burgerservicenummer of a Dutch citizen
type Bsn = string

// DiscoverableBy DiscoverableBy is a string that can be used to filter lists
type DiscoverableBy = string

// ReferenceDate reference date
type ReferenceDate = openapi_types.Date

// PathBSN Burgerservicenummer of a Dutch citizen
type PathBSN = Bsn

// QueryDiscoverableBy DiscoverableBy is a string that can be used to filter lists
type QueryDiscoverableBy = DiscoverableBy

// QueryLaw defines model for queryLaw.
type QueryLaw = string

// QueryReferenceDate reference date
type QueryReferenceDate = ReferenceDate

// QueryService defines model for queryService.
type QueryService = string

// BadRequestErrorResponse defines model for BadRequestErrorResponse.
type BadRequestErrorResponse struct {
	Errors []Error `json:"errors"`
}

// EvaluateResponse defines model for EvaluateResponse.
type EvaluateResponse struct {
	// Data Evaluate response
	Data EvaluateResponseSchema `json:"data"`
}

// InternalServerErrorResponse defines model for InternalServerErrorResponse.
type InternalServerErrorResponse struct {
	Errors []Error `json:"errors"`
}

// ProfileListResponse defines model for ProfileListResponse.
type ProfileListResponse struct {
	// Data List of all burgers
	Data ProfileList `json:"data"`
}

// ProfileResponse defines model for ProfileResponse.
type ProfileResponse struct {
	// Data Profile
	Data Profile `json:"data"`
}

// ResourceNotFoundErrorResponse defines model for ResourceNotFoundErrorResponse.
type ResourceNotFoundErrorResponse struct {
	Errors *[]Error `json:"errors,omitempty"`
}

// RuleSpecResponse defines model for RuleSpecResponse.
type RuleSpecResponse struct {
	// Data Rule spec
	Data RuleSpec `json:"data"`
}

// ServiceListResponse defines model for ServiceListResponse.
type ServiceListResponse struct {
	// Data List of all services
	Data ServiceList `json:"data"`
}

// EvaluateRequest defines model for EvaluateRequest.
type EvaluateRequest struct {
	// Data Evaluate.
	Data Evaluate `json:"data"`
}

// ServiceLawsDiscoverableListParams defines parameters for ServiceLawsDiscoverableList.
type ServiceLawsDiscoverableListParams struct {
	// DiscoverableBy Filter for discoverable by, defaults to 'CITIZEN'
	DiscoverableBy *QueryDiscoverableBy `form:"discoverableBy,omitempty" json:"discoverableBy,omitempty"`
}

// EvaluateJSONBody defines parameters for Evaluate.
type EvaluateJSONBody struct {
	// Data Evaluate.
	Data Evaluate `json:"data"`
}

// RuleSpecGetParams defines parameters for RuleSpecGet.
type RuleSpecGetParams struct {
	// Service filter for service
	Service QueryService `form:"service" json:"service"`

	// Law filter for law
	Law QueryLaw `form:"law" json:"law"`

	// ReferenceDate reference date
	ReferenceDate QueryReferenceDate `form:"reference_date" json:"reference_date"`
}

// EvaluateJSONRequestBody defines body for Evaluate for application/json ContentType.
type EvaluateJSONRequestBody EvaluateJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /discoverable-service-laws)
	ServiceLawsDiscoverableList(w http.ResponseWriter, r *http.Request, params ServiceLawsDiscoverableListParams)

	// (POST /evaluate)
	Evaluate(w http.ResponseWriter, r *http.Request)

	// (GET /profiles)
	ProfileList(w http.ResponseWriter, r *http.Request)

	// (GET /profiles/{bsn})
	ProfileGet(w http.ResponseWriter, r *http.Request, bsn PathBSN)

	// (GET /rule-spec)
	RuleSpecGet(w http.ResponseWriter, r *http.Request, params RuleSpecGetParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /discoverable-service-laws)
func (_ Unimplemented) ServiceLawsDiscoverableList(w http.ResponseWriter, r *http.Request, params ServiceLawsDiscoverableListParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /evaluate)
func (_ Unimplemented) Evaluate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /profiles)
func (_ Unimplemented) ProfileList(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /profiles/{bsn})
func (_ Unimplemented) ProfileGet(w http.ResponseWriter, r *http.Request, bsn PathBSN) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /rule-spec)
func (_ Unimplemented) RuleSpecGet(w http.ResponseWriter, r *http.Request, params RuleSpecGetParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ServiceLawsDiscoverableList operation middleware
func (siw *ServerInterfaceWrapper) ServiceLawsDiscoverableList(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ServiceLawsDiscoverableListParams

	// ------------- Optional query parameter "discoverableBy" -------------

	err = runtime.BindQueryParameter("form", true, false, "discoverableBy", r.URL.Query(), &params.DiscoverableBy)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "discoverableBy", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ServiceLawsDiscoverableList(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Evaluate operation middleware
func (siw *ServerInterfaceWrapper) Evaluate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Evaluate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ProfileList operation middleware
func (siw *ServerInterfaceWrapper) ProfileList(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ProfileList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ProfileGet operation middleware
func (siw *ServerInterfaceWrapper) ProfileGet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "bsn" -------------
	var bsn PathBSN

	err = runtime.BindStyledParameterWithOptions("simple", "bsn", chi.URLParam(r, "bsn"), &bsn, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bsn", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ProfileGet(w, r, bsn)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RuleSpecGet operation middleware
func (siw *ServerInterfaceWrapper) RuleSpecGet(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params RuleSpecGetParams

	// ------------- Required query parameter "service" -------------

	if paramValue := r.URL.Query().Get("service"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "service"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "service", r.URL.Query(), &params.Service)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "service", Err: err})
		return
	}

	// ------------- Required query parameter "law" -------------

	if paramValue := r.URL.Query().Get("law"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "law"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "law", r.URL.Query(), &params.Law)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "law", Err: err})
		return
	}

	// ------------- Required query parameter "reference_date" -------------

	if paramValue := r.URL.Query().Get("reference_date"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "reference_date"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "reference_date", r.URL.Query(), &params.ReferenceDate)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "reference_date", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RuleSpecGet(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/discoverable-service-laws", wrapper.ServiceLawsDiscoverableList)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/evaluate", wrapper.Evaluate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/profiles", wrapper.ProfileList)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/profiles/{bsn}", wrapper.ProfileGet)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/rule-spec", wrapper.RuleSpecGet)
	})

	return r
}

type BadRequestErrorResponseJSONResponse struct {
	Errors []Error `json:"errors"`
}

type EvaluateResponseJSONResponse struct {
	// Data Evaluate response
	Data EvaluateResponseSchema `json:"data"`
}

type InternalServerErrorResponseJSONResponse struct {
	Errors []Error `json:"errors"`
}

type ProfileListResponseJSONResponse struct {
	// Data List of all burgers
	Data ProfileList `json:"data"`
}

type ProfileResponseJSONResponse struct {
	// Data Profile
	Data Profile `json:"data"`
}

type ResourceNotFoundErrorResponseJSONResponse struct {
	Errors *[]Error `json:"errors,omitempty"`
}

type RuleSpecResponseJSONResponse struct {
	// Data Rule spec
	Data RuleSpec `json:"data"`
}

type ServiceListResponseJSONResponse struct {
	// Data List of all services
	Data ServiceList `json:"data"`
}

type ServiceLawsDiscoverableListRequestObject struct {
	Params ServiceLawsDiscoverableListParams
}

type ServiceLawsDiscoverableListResponseObject interface {
	VisitServiceLawsDiscoverableListResponse(w http.ResponseWriter) error
}

type ServiceLawsDiscoverableList200JSONResponse struct {
	ServiceListResponseJSONResponse
}

func (response ServiceLawsDiscoverableList200JSONResponse) VisitServiceLawsDiscoverableListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ServiceLawsDiscoverableList400JSONResponse struct {
	BadRequestErrorResponseJSONResponse
}

func (response ServiceLawsDiscoverableList400JSONResponse) VisitServiceLawsDiscoverableListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ServiceLawsDiscoverableList500JSONResponse struct {
	InternalServerErrorResponseJSONResponse
}

func (response ServiceLawsDiscoverableList500JSONResponse) VisitServiceLawsDiscoverableListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type EvaluateRequestObject struct {
	Body *EvaluateJSONRequestBody
}

type EvaluateResponseObject interface {
	VisitEvaluateResponse(w http.ResponseWriter) error
}

type Evaluate200JSONResponse struct{ EvaluateResponseJSONResponse }

func (response Evaluate200JSONResponse) VisitEvaluateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Evaluate400JSONResponse struct {
	BadRequestErrorResponseJSONResponse
}

func (response Evaluate400JSONResponse) VisitEvaluateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Evaluate500JSONResponse struct {
	InternalServerErrorResponseJSONResponse
}

func (response Evaluate500JSONResponse) VisitEvaluateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ProfileListRequestObject struct {
}

type ProfileListResponseObject interface {
	VisitProfileListResponse(w http.ResponseWriter) error
}

type ProfileList200JSONResponse struct {
	ProfileListResponseJSONResponse
}

func (response ProfileList200JSONResponse) VisitProfileListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ProfileList400JSONResponse struct {
	BadRequestErrorResponseJSONResponse
}

func (response ProfileList400JSONResponse) VisitProfileListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ProfileList500JSONResponse struct {
	InternalServerErrorResponseJSONResponse
}

func (response ProfileList500JSONResponse) VisitProfileListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ProfileGetRequestObject struct {
	Bsn PathBSN `json:"bsn"`
}

type ProfileGetResponseObject interface {
	VisitProfileGetResponse(w http.ResponseWriter) error
}

type ProfileGet200JSONResponse struct{ ProfileResponseJSONResponse }

func (response ProfileGet200JSONResponse) VisitProfileGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ProfileGet400JSONResponse struct {
	BadRequestErrorResponseJSONResponse
}

func (response ProfileGet400JSONResponse) VisitProfileGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ProfileGet404JSONResponse struct {
	ResourceNotFoundErrorResponseJSONResponse
}

func (response ProfileGet404JSONResponse) VisitProfileGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ProfileGet500JSONResponse struct {
	InternalServerErrorResponseJSONResponse
}

func (response ProfileGet500JSONResponse) VisitProfileGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RuleSpecGetRequestObject struct {
	Params RuleSpecGetParams
}

type RuleSpecGetResponseObject interface {
	VisitRuleSpecGetResponse(w http.ResponseWriter) error
}

type RuleSpecGet200JSONResponse struct{ RuleSpecResponseJSONResponse }

func (response RuleSpecGet200JSONResponse) VisitRuleSpecGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RuleSpecGet400JSONResponse struct {
	BadRequestErrorResponseJSONResponse
}

func (response RuleSpecGet400JSONResponse) VisitRuleSpecGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RuleSpecGet500JSONResponse struct {
	InternalServerErrorResponseJSONResponse
}

func (response RuleSpecGet500JSONResponse) VisitRuleSpecGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /discoverable-service-laws)
	ServiceLawsDiscoverableList(ctx context.Context, request ServiceLawsDiscoverableListRequestObject) (ServiceLawsDiscoverableListResponseObject, error)

	// (POST /evaluate)
	Evaluate(ctx context.Context, request EvaluateRequestObject) (EvaluateResponseObject, error)

	// (GET /profiles)
	ProfileList(ctx context.Context, request ProfileListRequestObject) (ProfileListResponseObject, error)

	// (GET /profiles/{bsn})
	ProfileGet(ctx context.Context, request ProfileGetRequestObject) (ProfileGetResponseObject, error)

	// (GET /rule-spec)
	RuleSpecGet(ctx context.Context, request RuleSpecGetRequestObject) (RuleSpecGetResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ServiceLawsDiscoverableList operation middleware
func (sh *strictHandler) ServiceLawsDiscoverableList(w http.ResponseWriter, r *http.Request, params ServiceLawsDiscoverableListParams) {
	var request ServiceLawsDiscoverableListRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ServiceLawsDiscoverableList(ctx, request.(ServiceLawsDiscoverableListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ServiceLawsDiscoverableList")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ServiceLawsDiscoverableListResponseObject); ok {
		if err := validResponse.VisitServiceLawsDiscoverableListResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Evaluate operation middleware
func (sh *strictHandler) Evaluate(w http.ResponseWriter, r *http.Request) {
	var request EvaluateRequestObject

	var body EvaluateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Evaluate(ctx, request.(EvaluateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Evaluate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(EvaluateResponseObject); ok {
		if err := validResponse.VisitEvaluateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ProfileList operation middleware
func (sh *strictHandler) ProfileList(w http.ResponseWriter, r *http.Request) {
	var request ProfileListRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ProfileList(ctx, request.(ProfileListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ProfileList")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ProfileListResponseObject); ok {
		if err := validResponse.VisitProfileListResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ProfileGet operation middleware
func (sh *strictHandler) ProfileGet(w http.ResponseWriter, r *http.Request, bsn PathBSN) {
	var request ProfileGetRequestObject

	request.Bsn = bsn

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ProfileGet(ctx, request.(ProfileGetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ProfileGet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ProfileGetResponseObject); ok {
		if err := validResponse.VisitProfileGetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RuleSpecGet operation middleware
func (sh *strictHandler) RuleSpecGet(w http.ResponseWriter, r *http.Request, params RuleSpecGetParams) {
	var request RuleSpecGetRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RuleSpecGet(ctx, request.(RuleSpecGetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RuleSpecGet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RuleSpecGetResponseObject); ok {
		if err := validResponse.VisitRuleSpecGetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZW28buxH+KwR7gPMiS7KdUyB6i2PFEOCqgWWgQF03oHZHEtNdckNyrSiC/nsxvOxd",
	"FyutEaB9k5bkXL6Z4X4zu6WRTDMpQBhNR1uaMcVSMKD8P7O6mU3xZww6UjwzXAo6oje5WoLSoF54BCJP",
	"U1BELggjt7mJViTihv8AQXuU424UQ3tUsBToiM41Lij4lnMFMR0ZlUOP6mgFKUNNvylY0BH906C0bOBW",
	"9QDP7nY9+i0HtbnlOpIvoNg8gZtN28hPPDGgyEIqEle2kvmmR2JYsDwxmhhJfv84eZz8fTz9PdhrpZcG",
	"x3U9p9raOFaYfc/WbVsXpa0JW+8xxK3sRw6+szRLcOcPqZZGgk7Ycg2G9qjZZPhcG8XFsrTlARagQERw",
	"ywy0rVJhmcS43m1VsemL33ReaFXNlMLCmcuxg4j5PNxjX7l6CnKPfx3P7j/cTccdoO2cCNDmRsYcbImM",
	"X1iSMwMPbgEfRVIYEPYny7KERwxNHnzVaPe2ojVTMgNlvKSYmaMgBW002OLceXKHnwuT5fwrRMaZXIft",
	"A9Emj0EYslRMGOJ2kjzD4BHvXr8FltOnMym0s/aGxd7lsVJSPfi1V/lfoL6lgEI0HT1taQpasyV6sZCS",
	"rNHUtZIYgOddr4FZOFaRdVhCj3IDqT6KM8qluwJPphTbtED32k+BfSJeWMJjwkWWG6JzxAXiPqooM+gM",
	"CM9PoaBu5mSdnVBBHgnpgT5NhAElWILVC+r/GXJShjjI7G0GitijNkE+K7ngCdxzbd4oRyoaz08ML4Qk",
	"XJtacviFt/Xl5/2ouvAAWuYqgqk0n2Qu4v+tDD8KWYCHCGnIAgGyifyQJzDLIHqjyAd154ceJRCdQVQL",
	"vqckb1iPFY3nO3PP1s1a3AUO5KiMDXiLaD2uwF1GxKyYITKKcgUxWa+wKDIlI9CaiyUxK66rBKLuZpGP",
	"VbLVSM0umlp1Nchoe1u+Rdv2hxW0qVJtSKY7iHJgiwUTHE9pq+RYlin5gkY1lUmRbEiugYQtJEoYT3XR",
	"cWDDgYSqdHYuZQJMoJa404GPTJA5oNQYT2NPsVbcADErR8zd0nxjH5R0t8T5anj1x8Xw8uL6kvboQqqU",
	"GexrHF1vYI4kOstdGscxRxtY8rnufudzx6lbgWk9SLr6H6xTvnAeJGztUk0AxLZDmwOB7xDlBuIug2Vu",
	"vMV1odoLZSEtISZuL8Gc6HS+3gC/ylO9r1WpOuc3vcbBRhWUAUYkD9VCg+LtrYzyRmgm+pFU2ANEyu2N",
	"8FAY3VT8N54k6DOeJ+sVCB8i3O1CQ7gmXkxnpZQhf5VlXkmKt+tfwJxkWZKQ6jF8qoCk1ba6YpjKE8C8",
	"m3S4PcG+iy+4G5ZgNoTd1bLMc348Cbz/oVjbntUsaYekK206BxP3duZQuTerY40v8w0a4+cnKNT33Gsw",
	"X7j4l0y1ATGHhGkT6qv+8msKa8VjJUnERDHAcW8ZPyIJLKZVxHXGEqxqyp6yFEIgnMTDmFspvZbNXVAG",
	"0tnSGRaaQMy1OGn21XipN8Xflv+CZ3M7quu66o6jsv+s43f60FviIKGxx2l7OpEkxIu2kx1GIlCGcYFE",
	"wwPXJDr1ILnpYghVRXhp84GAWYbVrgFkTXJhrwIHiaYnkuii+2gnZUFPj1xieygp7fBi77Bs1iYFlgG5",
	"buOnSrrccTO+/zB7nEzvbifj6eyxXe1O4fY05PDiObmUvX/Ex/2kOrbWPO9H8Xgu+DfxyckQotDhli+I",
	"A+VUaDiHfRV6WsNAp7fjpL+Rzpz7l9zz8vLy6urq+voa7zxmDCgU9M+n4cX75+373W9dt0t8ZLJfn/wj",
	"V2DEnXa8KqozZj8qxuZH12wLWd5hgnrlZPw8sr2zdHsh7VuMG3se+zSmyUcZ44EXUNqpHPaH/UvLfTIQ",
	"LON0RK/7w77HdWVzo/bR4cLH6SLU3bKL8dyBsclc+0QSWOo/8uHw6s/ECrCKlW1qkdwUZcLWuhoPWzZ1",
	"Hv3UXRbllkHX9xy8WWoj56vhcF+FFfsGXc35rkffnXJ230x716N/nHL+0NTTzk3YEtGwnOoZHwyg0rVm",
	"suu+KTh6yVLqYSga3+rHic1+YyvfLwbNjxe7cxBvza9/Xbg9iTheDMXGJtpVnnAOWF2z3F8Nr8BZ6pgN",
	"tnMtdj+N3B28/nYIn6HPuxGa4+b/ANzvhu+Onz88I/7vBg17vwvtyeXeeKkKl6wHK3DTc6JV+2y76522",
	"37G90/bWP1qflxStUfQvemn5sVKAPlcJHdGVMZkeDQYs43232jegzeDl0qLhRWwDLw/Y+r9FS/K8+3cA",
	"AAD//xOSH9n+IQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
