apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lac
namePrefix: dji-

patches:
  - target:
      kind: Ingress
      name: backend-ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: dji-backend.127-0-0-1.nip.io
      - op: remove
        path: /spec/tls
  - target:
      kind: Ingress
      name: inzicht-backend-ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: dji-inzicht-backend.127-0-0-1.nip.io
      - op: remove
        path: /spec/tls

resources:
  - ../../base
