apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: machine
  template:
    metadata:
      labels:
        app: machine
      annotations:
        sidecar.opentelemetry.io/inject: "cbs-machine-otlp-collector"
    spec:
      containers:
        - name: cbs-machine
          image: go-engine-image
          env:
            - name: APP_DEBUG
              value: "true"
            - name: APP_ORGANIZATION
              value: "CBS"
            - name: APP_STANDALONE_MODE
              value: "true"
            - name: APP_RULE_SERVICE_IN_MEMORY
              value: "false"
            - name: APP_LDV_ENABLED
              value: "true"
            - name: APP_LDV_ENDPOINT
              value: "localhost:4317"
            - name: APP_EXTERNAL_CLAIM_RESOLVER_ENDPOINT
              value: "http://belastingdienst-backend-svc/"
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: services-config
              mountPath: /build/services
              readOnly: true
      volumes:
        - name: services-config
          configMap:
            name: services-cm
