engines:
  - id: py
    name: Python engine
    description: default processing engine
    type: internal
  - id: go
    name: Go engine
    description: typed processing engine (beta)
    type: http
    domain: http://localhost:8081/v0
    default: true
