name: Docker Build Validation

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Kaniko build (no push)
      uses: aevea/action-kaniko@v0.10.0
      with:
        no_push: true
        build_file: Dockerfile
