name: Build image and push to GitHub Container Registry

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Lowercase the GitHub repository
      id: lowercase-repository
      run: |
        echo "github_repository=${{ github.repository }}" >> $GITHUB_OUTPUT

    - name: Build and Push Image with Kaniko
      uses: int128/kaniko-action@v1
      with:
        push: true
        tags: ghcr.io/${{ steps.lowercase-repository.outputs.github_repository }}/poc:${{ github.sha }}-${{ github.ref_name }}-${{ github.run_id }}
        cache: true
        cache-ttl: 168h
        cache-repository: ghcr.io/${{ github.repository }}/cache
